name             'delivery-golang'
maintainer       'Chef Delivery Team'
maintainer_email 'delivery-team@chef.io'
license          'Apache-2.0'
description      'Installs/Configures Golang Applications'
version          '0.2.0'
